### ISSUE TITLE
no Kernel 

### ISSUE THREAD

**Issue by Noname400** [kanhavishva/PubHunt#1]
GPUEngine: callKernel: no kernel image is available for execution on the device
![image](https://user-images.githubusercontent.com/74019756/123292501-89140500-d52c-11eb-82ea-df275bd3a15e.png)

**Comment by kanhavishva** [comment]
Sorry I have forgot to build for other cuda caps, have updated the binary, try now.

**Comment by Noname400** [comment]
Moment

**Comment by Noname400** [comment]
work!

**Comment by kanhavishva** [comment]
👍
