### ISSUE TITLE
off topic question

### ISSUE THREAD

**Issue by Noname400** [kanhavishva/PubHunt#3]
Have you considered the option of choosing the BIP39 phrase for solving the puzzle?

**Comment by kanhavishva** [comment]
No I don't think that brute forcing the BIP39 phrase would be easier is this case, because he/she modified them manually.
Look at the message from the puzzle creator:

He/She is saying that keys are derived from deterministic wallet but modified to create consecutively increased difficulties.


![500047300240_326457](https://user-images.githubusercontent.com/24961687/123423054-aef8e280-d5dc-11eb-9b76-0fb2836bc0a6.jpg)

**Comment by Noname400** [comment]
if I do not think correctly, correct me
compress public key 02 or 03 (ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff) = 115792089237316195423570985008687907853269984665640564039457584007913129639935 combinations
BIP39 english 2048 ^12 = 5444517870735015415413993718908291383296

**Comment by Noname400** [comment]
(masked with leading 000...0001 to set difficulty)  I think this can also be calculated.

**Comment by kanhavishva** [comment]
Not all from 0 to 2^256 values are valid public keys for bitcoin curve.
Curve order for secp256k1 is FFFFFFFF FFFFFFFF FFFFFFFF FFFFFFFE BAAEDCE6 AF48A03B BFD25E8C D0364141.
This value defines the total possible valid private keys for bitcoin curve, so we choose a value between 0 and curve order, then do scalar multiplication with curve generator to get public key point, now this public key point is fixed on the curve for this particular private key. 

This means total possible valid public keys are also same as curve order. so not every point in 0 to cure order range is a valid point.

BIP39 with 12 words only provides 128 bits security, and with 24 words it is 256 bits.

It is possible to do brute force in that way too but it will be hard as that much. 
The process of generating mnemonic to public key is also computationally intensive work, so the speed of scanning will not be that much faster.

By brute forcing we can't even break 64 bits security, so 128 bits is really really far away.

**Comment by kanhavishva** [comment]
and we don't even know whether the puzzle creator used 12 words or 24 words mnemonic 🤣

**Comment by Noname400** [comment]
you are probably right. but I will try.
