### ISSUE TITLE
why pubhunt start from 30bit

### ISSUE THREAD

**Issue by makabress** [kanhavishva/PubHunt#6]
hi
thank you for your work
im trying to understand how it work
i see it start at 30bit , 30bit of what? pubkey ,privkey or hash160
i can't get any result starting from adresses with 1 bit privkey to 40bit
can you explain pls

**Comment by kanhavishva** [comment]
It doesn't search for privkeys, rather than it generate random compressed pubkeys, hash them and check in given keys, thats it.

look at this: https://github.com/kanhavishva/PubHunt/issues/5#issuecomment-869017849

**Comment by kanhavishva** [comment]
and how did you figured out this 30 bit thing?

**Comment by makabress** [comment]
> and how did you figured out this 30 bit thing?

Just when i start searching it show from 3Xbit to 42bit after few moment

**Comment by makabress** [comment]
> It doesn't search for privkeys, rather than it generate random compressed pubkeys, hash them and check in given keys, thats it.
> 
> look at this: [#5 (comment)](https://github.com/kanhavishva/PubHunt/issues/5#issuecomment-869017849)
I think 

> It doesn't search for privkeys, rather than it generate random compressed pubkeys, hash them and check in given keys, thats it.
> 
> look at this: [#5 (comment)](https://github.com/kanhavishva/PubHunt/issues/5#issuecomment-869017849)

I think if you want make collision in pubkey better make multiplication between list of the first 256 pubkey with a random 56bit hex just un exemple

I don't think it's possible to collid with the pubkey of one address by full random. you need a list of trillions of hash160 to have 1 chance in few years

I like the idea of searching pubkey, maybe every radomized pubkey need addition and subtraction to cover more surface rather than attacking by point

I believe the multiplication + addition and subtraction of every pubkey is a way to attack the 64bit address

Anyway thank you for this work
